@Library('mylibrary')_
node('built-in')
{
    stage('ContinuousDownload_master')
    {
        cicd.newgit("https://github.com/intelliqittrainings/maven.git")
    }
    stage('ContinuousBuild_master')
    {
       cicd.newbuild()
    }
}
